# Generated by Django 5.0.2 on 2024-04-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital_book_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
