# Generated by Django 5.0.2 on 2024-08-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='add_to_cart',
            new_name='added_to_cart',
        ),
        migrations.RenameField(
            model_name='interaction',
            old_name='likes',
            new_name='liked',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
