# Generated by Django 5.0.2 on 2024-04-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_digital_book_url_product_digital_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='cover_photo',
        ),
    ]
