# Generated by Django 5.0.2 on 2024-04-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_author_remove_product_authors_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publication_date',
            field=models.IntegerField(),
        ),
    ]
